name: Ruff Linter Check

on:
  pull_request_target:
  push:
    branches:
      - main  # or whichever branches you want to lint

jobs:
  ruff:
    name: Run Ruff Linter and Check Config Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Adjust to the Python version used in your app

      - name: Fetch main branch for comparison
        run: git fetch origin main

      - name: Check for configuration file changes
        run: |
          # Compare current config files with those in the main branch.
          if git diff --name-only origin/main | grep -E '^(pyproject\.toml|\.editorconfig)$'; then
            echo "Error: Configuration files (pyproject.toml or .editorconfig) have been modified. Please revert these changes.";
            exit 1;
          else
            echo "Configuration files unchanged.";
          fi

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff linter
        run: ruff check .
