name: Lint, Format, and Indentation Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install ruff black

      - name: Run Ruff Linter
        run: |
          ruff check .

      - name: Check Code Formatting with Black
        run: |
          black --check .

      - name: Check for Tab Characters in Python Files
        run: |
          echo "Searching for tab characters in Python files..."
          if grep -R --include="*.py" -n $'\t' .; then
            echo "Tab characters found! Please use spaces for indentation."
            exit 1
          else
            echo "No tab characters found."
          fi
